name: Build Containerimage

on:
  push:
    tags:
      - 'v*.*.*'
  schedule:
    - cron: '55 10 * * *'

jobs:
  push_to_registry:
    name: Push detour-proxy to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build
        run: docker build . --file Dockerfile --tag ${{ vars.DOCKER_ORG }}/detour:${{ steps.vars.outputs.tag }} --tag ${{ vars.DOCKER_ORG }}/detour:latest

      - name: push
        run: docker image push --all-tags ${{ vars.DOCKER_ORG }}/detour

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: pulsiot/detour
